# Generated by Django 4.2 on 2023-04-14 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_customer_faq_package_room_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 4, 14, 2, 43, 26, 495525, tzinfo=datetime.timezone.utc)),
        ),
    ]
