# Generated by Django 4.2 on 2023-04-14 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_customer_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
