# Generated by Django 4.2 on 2023-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_customer_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coupon',
            field=models.IntegerField(default=0),
        ),
    ]
