# Generated by Django 4.2 on 2023-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_customer_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
