# Generated by Django 4.2 on 2023-04-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_customer_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='rank',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rank',
        ),
    ]
