# Generated by Django 4.2 on 2023-04-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_copuon_packagedetails_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='coupon',
        ),
    ]
