# Generated by Django 4.2 on 2023-04-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rename_room_space_rename_room_booking_space'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date']},
        ),
    ]
