# Generated by Django 4.2 on 2023-04-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='terms',
            field=models.TextField(default='Terms'),
            preserve_default=False,
        ),
    ]
