# Generated by Django 4.2 on 2023-04-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_company_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(default='http://cany.pythonanywhere.com'),
            preserve_default=False,
        ),
    ]
