# Generated by Django 4.2 on 2023-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='cleanUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('credits', models.IntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
