# Generated by Django 4.2 on 2023-05-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_rename_coupon_package_credits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagedetails',
            options={'ordering': ['dueDate']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_joined',
        ),
    ]
