# Generated by Django 4.2 on 2023-05-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_contact_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
