# Generated by Django 4.2 on 2023-05-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_customer_gender_alter_customer_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(default='', max_length=16),
        ),
    ]
