# Generated by Django 4.2 on 2023-05-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_alter_customer_gender_alter_customer_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='long_name',
            field=models.CharField(default='w3Space Limited', max_length=255),
            preserve_default=False,
        ),
    ]
