# Generated by Django 4.2 on 2023-05-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_company_long_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='city',
            field=models.CharField(default='Hong Kong', max_length=64),
            preserve_default=False,
        ),
    ]
