# Generated by Django 4.2 on 2023-05-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_space_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'question']},
        ),
        migrations.AddField(
            model_name='space',
            name='area',
            field=models.CharField(default='Kwai CHun KLN', max_length=255),
            preserve_default=False,
        ),
    ]
