# Generated by Django 4.2 on 2023-05-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_alter_faq_options_space_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='space',
            name='is_space',
            field=models.BooleanField(default=True),
        ),
    ]
